apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api 
  namespace: todo-api
spec:
  project: default
  source:
    repoURL: https://github.com/thanhtu3012/My-FreeTime-Manifest.git
    targetRevision: main
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
