apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-api
  namespace: todo-api
  annotations:
    todo-api-image-updater.argoproj.io/image-list: todo-api=galaxy121996/todo-api:v1.0.x
    todo-api-image-updater.argoproj.io/todo-api.update-strategy: semver
    todo-api-image-updater.argoproj.io/todo-api.allow-tags: regexp:^v?[0-9]+\.[0-9]+\.[0-9]+$
    todo-api-image-updater.argoproj.io/write-back-method: git
    todo-api-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/thanhtu3012/My-FreeTime-Manifest.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
