apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  annotations:
    # image updater config
    todo-api-image-updater.argoproj.io/image-list: todo-api=galaxy121996/todo-api
    todo-api-image-updater.argoproj.io/todo-api.update-strategy: semver
    todo-api-image-updater.argoproj.io/todo-api.allow-tags: regexp:^v?[0-9]+\.[0-9]+\.[0-9]+$
    todo-api-image-updater.argoproj.io/write-back-method: git
    todo-api-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: galaxy121996/todo-api:v1.0.0
          ports:
            - containerPort: 8080
